from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from moveit_configs_utils import MoveItConfigsBuilder

def generate_launch_description():
    # 1. Declare arguments
    declared_arguments = []
    declared_arguments.append(
        DeclareLaunchArgument(
            "use_sim_time",
            default_value="true",
            description="Use simulation (Gazebo) clock if true",
        )
    )
    
    use_sim_time = LaunchConfiguration("use_sim_time")

    # 2. Load MoveIt Config
    moveit_config = (
        MoveItConfigsBuilder("parallel_beam_gantry", package_name="gantry_moveit_config_2")
        .to_moveit_configs()
    )

    # 3. Resolve path to RViz config generated by Setup Assistant
    rviz_config_file = PathJoinSubstitution(
        [FindPackageShare("gantry_moveit_config_2"), "config", "moveit.rviz"]
    )

    # 4. Start RViz Node
    # We inject robot_description_semantic and use_sim_time here
    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="log",
        arguments=["-d", rviz_config_file],
        parameters=[
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,  # <--- Crucial for "No Planning Group" error
            moveit_config.robot_description_kinematics,
            moveit_config.planning_pipelines,
            moveit_config.joint_limits,
            {"use_sim_time": use_sim_time},
        ],
    )

    return LaunchDescription(declared_arguments + [rviz_node])